platform :ios, '13.0'
inhibit_all_warnings!

target 'PicturesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PicturesApp
   pod 'SwiftLint'
   pod 'Moya', '~> 13.0'
   pod 'Kingfisher'

end

post_install do |installer|

  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end

