platform :ios, '13.0'
inhibit_all_warnings!

target 'Septa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Septa
   pod 'SwiftLint'
   pod "PromiseKit/CoreLocation"
end
